import 'package:get/get.dart';

class TransLanguage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'landingViewText': 'Manage your reservations',
          'landingBtnText': 'Get Started',
          'loginText': 'Login',
          'nameFieldText': 'Name',
          'rememberText': 'Remember Me',
          'nameHintText': 'Your Restaurant Name',
          'emailFieldText': 'Email Address',
          'emailHintText': 'Your email Address',
          'enterEmailHintText': 'Example@gmail.com',
          'resetPasswordTitle': 'Reset Password',
          'resetDescription': 'Please type something you’ll remember',
          'createPasswordFieldText': 'Create a password',
          'sendText': 'Send code',
          'enterText': 'Enter Code',
          'accountSettingText': 'Account Settings',
          'forgetText': 'Forget Password?',
          'forgetDescription':
              'Don’t worry! It happens. Please enter the email associated with your account',
          'lgOutText': 'logout',
          'enterEmailText': 'Enter your email address',
          'verifyText': 'Verify',
          'repeatPassHintText': 'Repeat password',
          'successPassDes': 'Your Password Has been Changed Successfully',
          'passChangeText': 'Password changed',
          'activationText':
              'We’ve sent an SMS with an activation code to your phone number  ',
          'sendCodeTitle': 'Please Check Your Email',
          'sendCodeDes': 'We’ve sent a code to your email ',
          'passwordFieldText': 'Create a new password',
          'passwordConfirmFieldText': 'Confirm Password',
          'confirmPassFieldText': 'Confirm password',
          'resetBtnText': 'Reset Password',
          'loginBtnText': 'Back to login',
          'phoneValidatorText': 'phone too long',
          'searchLabelText': 'Search',
          'passwordText': 'Password',
          'nameTooLong': 'Name too long',
          'bookedReservation': 'We’ve successfully booked your reservation',
          'acceptedText': 'Reservation Accepted ',
          'summaryText': 'Reservation Summary ',
          
          'validEmail': 'Please enter a valid email',
          'charactersPassHintText': 'Must be 8 characters',
          'phoneFieldText': 'Phone number',
          'validatorText': 'Please fill in this field',
          'noUpcomingText': 'No upcoming reservations',
          'pastText': 'Past Reservations',
          'noPastComingText': 'No Past Reservations',
          'upcomingText': 'Upcoming Reservations',
          'noPastReservation': 'No past reservations',
          'pastCancelledText':'No cancelled reservations',
          'phoneHintText':'enter your phone number',
          'phoneShortValidatorText':'phone too short',
          'approvedPastComingText':"No upcoming reservations",
           'pastPendingText': 'Past Pending Reservations List is Empty',
          'noReservationsText': 'No Reservations',
          'presentPendingText':'No upcoming reservations',
          'totalReservation': 'Total reservation today',
          'profileText': 'Restaurant Profile',
          'cancelText': 'Cancel',
          'reservationText': 'Reservations',
          'contactText': 'Contact Us',
          'accountSettings': 'Account Settings',
          'nameText': "Name",
          'emailText': "Email ",
          'phoneText': "Phone Number ",
          'messageText': 'Message',
          'messageTextDes': 'Write Down Your  Query Here',
          'submitText': 'Submit',
          'incomingText': 'UPCOMING',
          'todayText': 'TODAY',
          'guestReservationText': 'Guest made a reservation at',
          'peopleText': 'People',
          'alertText': 'New Reservation Alert',
          'favList': 'Favorite List is Empty',
          'searchListEmpty': 'Search List is Empty ',
          'confirmedText': 'Confirmed',
          'logoutTitle': 'Want to Logout?',
          'logoutDes':
              'Click On The Logout Button If You Really Want to Logout?',
          'logoutText': 'Logout',
        },
      };
}
