// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiA6qTnIHqKwqZdXrXaSb6teqRYAR2V4E',
    appId: '1:1037240109968:android:2bdf52e98f8d160fcb8115',
    messagingSenderId: '1037240109968',
    projectId: 'mylunchicapp',
    storageBucket: 'mylunchicapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRGMYUn6fcrj38YpM1meyUeLjXzzHfanA',
    appId: '1:1037240109968:ios:a9af8aaeadd719edcb8115',
    messagingSenderId: '1037240109968',
    projectId: 'mylunchicapp',
    storageBucket: 'mylunchicapp.appspot.com',
    androidClientId: '1037240109968-gu6dtoc2oq1to9rq0hheo8e1vgkb094t.apps.googleusercontent.com',
    iosClientId: '1037240109968-tqtou3d8vs20lf0g7mug8upog1f5csb1.apps.googleusercontent.com',
    iosBundleId: 'com.lunchic.resturants',
  );
}
