// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX9Nw4onqtHilTQeb91X6MNPbikrYn4Ls',
    appId: '1:852110642735:android:edce2a36d423cf171700da',
    messagingSenderId: '852110642735',
    projectId: 'lunchicapp-8ce3e',
    storageBucket: 'lunchicapp-8ce3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeLCChrIWubLzkDQkHEjrfy8mTShJNZ3Q',
    appId: '1:852110642735:ios:8ef4f97d360bedbf1700da',
    messagingSenderId: '852110642735',
    projectId: 'lunchicapp-8ce3e',
    storageBucket: 'lunchicapp-8ce3e.firebasestorage.app',
    androidClientId: '852110642735-bqhn03f93bkink242vifm0pjpps34i5l.apps.googleusercontent.com',
    iosClientId: '852110642735-dk2up7lkgfkpcjv84o3jc0jmb2d97o1a.apps.googleusercontent.com',
    iosBundleId: 'com.lunchic.resturant',
  );
}
